version: "3.5"
services:
  admin:
    image: nginx:stable
    container_name: admin-prod
    ports:
      - "9000:80"
    volumes:
      - ./admin/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./admin/html:/usr/share/nginx/html
    depends_on:
      - backend
  backend:
    image: openjdk:11
    container_name: backend-prod
    volumes:
      - ./backend/sitmun-backend-core.jar:/opt/sitmun/backend.jar
    ports:
      - "9001:8080"
    environment:
      - "spring.profiles.active=prod"
      - "spring.datasource.url=jdbc:postgresql://postgres:5432/stm3"
      - "spring.datasource.username=stm3"
      - "spring.datasource.password=stm3"
      - "spring.datasource.hikari.auto-commit=false"
      - "spring.jpa.properties.hibernate.dialect=org.sitmun.plugin.core.tools.PostgresSQL93DialectFixed"
      - "spring.liquibase.run-async=true"
      - "server.forward-headers-strategy=framework"
      - "TZ=CET"
    command: [ 'java', '-jar', '/opt/sitmun/backend.jar' ]
    depends_on:
      - postgres
  postgres:
    image: postgres:9.3-alpine
    container_name: postgres-db-prod
    ports:
      - "9432:5432"
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgres/scripts/:/docker-entrypoint-initdb.d