version: "3.5"
services:
  admin:
    image: nginx:stable
    ports:
      - "8000:80"
    volumes:
      - ./admin/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./admin/html:/usr/share/nginx/html
  backend:
    image: openjdk:11
    volumes:
      - ./backend/sitmun-backend-core.jar:/opt/sitmun/backend.jar
    ports:
      - "8001:8080"
    environment:
      - "spring.profiles.active=dev"
      - "spring.datasource.url=jdbc:oracle:thin:@oracle:1521:xe"
      - "spring.datasource.username=stm3"
      - "spring.datasource.password=stm3"
      - "spring.datasource.hikari.auto-commit=false"
      - "spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.Oracle10gDialect"
      - "server.forward-headers-strategy=framework"
      - "TZ=CET"
    command: [ 'java', '-jar', '/opt/sitmun/backend.jar' ]
  oracle:
    image: oracle/database:11.2.0.2-xe
    container_name: oracle-db
    shm_size: '1500000000'
    ports:
      - "8002:8080"
      - "1521:1521"
    environment:
      - ORACLE_PWD=password
      - ORACLE_CHARACTERSET=AL32UTF8
    volumes:
      - ./oracle/scripts/setup:/u01/app/oracle/scripts/setup